name: ci

on:
  push:
    branches: [ main, dev ]
    paths-ignore:
      - '**/coverage.info'
      - '**/coverage.xml'
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    name: ${{ matrix.os }} - ${{ matrix.arch }} - ${{ matrix.compiler }} - ${{ matrix.build_type }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest ]
        arch: [ arm64 ]
        compiler: [ clang ]
        build_type: [ Release ]

    env:
      BUILD_TYPE: ${{ matrix.build_type }}
      CCACHE_DIR: ${{ github.workspace }}/.ccache

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache Homebrew
        uses: actions/cache@v4
        with:
          path: /opt/homebrew
          key: homebrew-${{ runner.os }}-${{ runner.arch }}-${{ github.sha }}
          restore-keys: |
            homebrew-${{ runner.os }}-${{ runner.arch }}-
            homebrew-${{ runner.os }}-

      - name: Install Homebrew Dependencies
        run: |
          if ! command -v brew &>/dev/null; then
            echo "Homebrew not found, installing..."
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          fi
          brew update
          brew install ccache llvm lcov

      - name: Cache ccache directory
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/.ccache
          key: ${{ runner.os }}-${{ matrix.arch }}-${{ matrix.compiler }}-${{ matrix.build_type }}-ccache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.arch }}-${{ matrix.compiler }}-${{ matrix.build_type }}-ccache-

      - name: Create Build Directory
        run: cmake -E make_directory ${{ github.workspace }}/build

      - name: Configure CMake
        working-directory: ${{ github.workspace }}/build
        run: |
          cmake .. \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -DCMAKE_C_COMPILER=clang \
            -DCMAKE_CXX_COMPILER=clang++ \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/install \
            -DBUILD_TESTING=ON \
            -DCMAKE_CXX_FLAGS="--coverage"

      - name: Build
        working-directory: ${{ github.workspace }}/build
        run: cmake --build . --config ${{ matrix.build_type }}

      - name: Run Tests
        working-directory: ${{ github.workspace }}/build
        run: |
          export GTEST_COLOR=yes
          ctest --output-on-failure -C ${{ matrix.build_type }} --verbose

      - name: Upload Test Logs
        if: always()
        uses: actions/upload-artifact@v4.4.3
        with:
          name: test-logs-${{ runner.os }}-${{ matrix.arch }}-${{ matrix.compiler }}-${{ matrix.build_type }}
          path: |
            ${{ github.workspace }}/build/Testing/Temporary/LastTest.log
            ${{ github.workspace }}/build/tests/test_detail.xml
          retention-days: 7
